### PR TITLE
Ready To Merge: Update README.md

### PR DESCRIPTION
**Pull request by tonynguyen111997**
This PR references issue #3 and will be focused on updating the README.md

To view current changes, go to **Code** tab and change to **update-readme** branch. If you scroll down you should see what the README.md looks like.

### CODE REVIEW

**Comment by tonynguyen111997** [comment]
Currently only **Getting Started** and **Contributing To The Project** links work, since the rest don't have markdown files yet.

**Comment by tonynguyen111997** [comment]
As of now **Getting Started**, **Front-End Technology**, **Contributing To The Project** and **Design** links work. 

**Testing**, **Style Guide** and **Troubleshooting** links are still not working because we need more information on these sections.

**Comment by tonynguyen111997** [comment]
Can someone review these changes and see if anything is still missing? If nothing is missing, then this PR should be ready to merge.

**Comment by lloan** [comment]
Lots of work put into this - great job @tonynguyen111997!

**Pull request merged**
